<div data-role="page" id="spellingalphabet-01-index">
	<div data-role="header" data-position="fixed">
		<div data-role="controlgroup" data-type="horizontal" class="ui-mini ui-btn-left">
			<a href="#function-99-navigationpanel" class="ui-btn ui-btn-icon-right ui-icon-bars ui-btn-icon-notext">Menü</a>
			<a data-rel="back" class="ui-btn ui-btn-icon-right ui-icon-arrow-l ui-btn-icon-notext">Zurück</a>
		</div>
		<h1>Buchstabieralphabet</h1>
		<div data-role="controlgroup" data-type="horizontal" class="ui-mini ui-btn-right">
			<a href="#function-02-settings" class="ui-btn ui-btn-icon-right ui-icon-gear ui-btn-icon-notext" data-transition="slidefade" data-direction="reverse">Einstellungen</a>
			<a href="#main-02-index" class="ui-btn ui-btn-icon-right ui-icon-home ui-btn-icon-notext">Home</a>
		</div>
	</div>
	<div data-role="content" role="main" class="ui-content">
		<table data-role="table" id="spellingalphabet-01-spellingalphabet-table" data-mode="columntoggle" class="ui-body-d ui-shadow table-stripe ui-responsive" data-column-btn-theme="a" data-column-btn-text="Alphabete" data-column-popup-theme="c">
			<thead>
				<tr>
					<th>Buchstabe</th>
					<th data-priority="1">Deutschland</th>
					<th data-priority="2">NATO</th>
				</tr>
			</thead>
			<tbody>
				<tr>
					<th>A</th>
					<td>Anton</td>
					<td>Alfa</td>
				</tr>
				<tr>
					<th>Ä</th>
					<td>Ärger</td>
					<td>Alfa-Echo</td>
				</tr>
				<tr>
					<th>B</th>
					<td>Berta</td>
					<td>Bravo</td>
				</tr>
				<tr>
					<th>C</th>
					<td>Cäsar</td>
					<td>Charlie</td>
				</tr>
				<tr>
					<th>Ch</th>
					<td>Charlotte</td>
					<td>Charlie-Hotel</td>
				</tr>
				<tr>
					<th>D</th>
					<td>Dora</td>
					<td>Delta</td>
				</tr>
				<tr>
					<th>E</th>
					<td>Emil</td>
					<td>Echo</td>
				</tr>
				<tr>
					<th>F</th>
					<td>Friedrich</td>
					<td>Foxtrot</td>
				</tr>
				<tr>
					<th>G</th>
					<td>Gustav</td>
					<td>Golf</td>
				</tr>
				<tr>
					<th>H</th>
					<td>Heinrich</td>
					<td>Hotel</td>
				</tr>
				<tr>
					<th>I</th>
					<td>Ida</td>
					<td>India</td>
				</tr>
				<tr>
					<th>J</th>
					<td>Julius</td>
					<td>Juliett</td>
				</tr>
				<tr>
					<th>K</th>
					<td>Kaufmann</td>
					<td>Kilo</td>
				</tr>
				<tr>
					<th>L</th>
					<td>Ludwig</td>
					<td>Lima</td>
				</tr>
				<tr>
					<th>M</th>
					<td>Martha</td>
					<td>Mike</td>
				</tr>
				<tr>
					<th>N</th>
					<td>Nordpol</td>
					<td>November</td>
				</tr>
				<tr>
					<th>O</th>
					<td>Otto</td>
					<td>Oscar</td>
				</tr>
				<tr>
					<th>Ö</th>
					<td>Ökonom</td>
					<td>Oscar-Echo</td>
				</tr>
				<tr>
					<th>P</th>
					<td>Paula</td>
					<td>Papa</td>
				</tr>
				<tr>
					<th>Q</th>
					<td>Quelle</td>
					<td>Quebec</td>
				</tr>
				<tr>
					<th>R</th>
					<td>Richard</td>
					<td>Romeo</td>
				</tr>
				<tr>
					<th>S</th>
					<td>Samuel</td>
					<td>Sierra</td>
				</tr>
				<tr>
					<th>Sch</th>
					<td>Schule</td>
					<td></td>
				</tr>
				<tr>
					<th>ß</th>
					<td>Eszett</td>
					<td>Sierra-Sierra</td>
				</tr>
				<tr>
					<th>T</th>
					<td>Theodor</td>
					<td>Tango</td>
				</tr>
				<tr>
					<th>U</th>
					<td>Ulrich</td>
					<td>Uniform</td>
				</tr>
				<tr>
					<th>Ü</th>
					<td>Übermut</td>
					<td>Uniform-Echo</td>
				</tr>
				<tr>
					<th>V</th>
					<td>Viktor</td>
					<td>Viktor</td>
				</tr>
				<tr>
					<th>W</th>
					<td>Wilhelm</td>
					<td>Whiskey</td>
				</tr>
				<tr>
					<th>X</th>
					<td>Xanthippe</td>
					<td>X-Ray</td>
				</tr>
				<tr>
					<th>Y</th>
					<td>Ypsilon</td>
					<td>Yankee</td>
				</tr>
				<tr>
					<th>Z</th>
					<td>Zacharias</td>
					<td>Zulu</td>
				</tr>
			</tbody>
		</table>
	</div>
</div>